name: cibuildwheel

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.arch }} ${{ matrix.distro }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [ubuntu-18.04, macos-latest]
#        include:
#          - arch: aarch64
#            distro: ubuntu-18.04
#          - arch: aarch64
#            distro: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.4

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        env:
          CIBW_BUILD: "cp37-*"
          CIBW_BEFORE_BUILD: 'source .travis/install_cargo.sh'
          CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH"'
          CIBW_ENVIRONMENT_MACOS: 'MACOSX_DEPLOYMENT_TARGET=10.11'
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_MANYLINUX_I686_IMAGE: manylinux1
          CIBW_BUILD_VERBOSITY: 3
        run: |
          python -m cibuildwheel --output-dir dist

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
